from pydantic import BaseModel, Field
from datetime import date
from typing import Optional, List

class CRBookInfo(BaseModel):
    cr_book_number: Optional[str] = Field(..., description="CR book number")
    registration_number: Optional[str] = Field(..., description="Vehicle registration number")
    chassis_number: Optional[str] = Field(..., description="Chassis number of the vehicle")
    engine_number: Optional[str] = Field(..., description="Engine number of the vehicle")
    cylinder_capacity: Optional[str] = Field(..., description="Cylinder capacity of the vehicle")
    class_of_vehicle: Optional[str] = Field(..., description="Class of the vehicle (e.g., Motorcycle, Car)")
    taxation_class: Optional[str] = Field(..., description="Taxation class of the vehicle")
    status_when_registered: Optional[str] = Field(..., description="Status of the vehicle when registered (e.g., Brand New, Reconditioned)")
    fuel_type: Optional[str] = Field(..., description="Fuel type of the vehicle (e.g., Petrol, Diesel)")
    provincial_council: Optional[str] = Field(None, description="Provincial council of registration if available")
    date_of_registration: Optional[date] = Field(None, description="Date of registration in YYYY-MM-DD format")
    owner_name: Optional[str] = Field(None, description="Name of the current owner")
    absolute_owner: Optional[str] = Field(None, description="Name of the absolute owner")
    absolute_owner_reference_date: Optional[date] = Field(None, description="Reference date for absolute owner")
    previous_owners: Optional[int] = Field(None, description="Number of previous owners")
    previous_owner_details: Optional[List[str]] = Field(None, description="List of previous owner details")
    make: Optional[str] = Field(None, description="Make of the vehicle")
    model: Optional[str] = Field(None, description="Model of the vehicle")
    color: Optional[str] = Field(None, description="Color of the vehicle")
    year_of_manufacture: Optional[int] = Field(None, description="Year of manufacture")
    country_of_origin: Optional[str] = Field(None, description="Country of origin of the vehicle")
    wheelbase: Optional[str] = Field(None, description="Wheelbase of the vehicle")
    seating_capacity: Optional[str] = Field(None, description="Seating capacity of the vehicle")
    gross_weight: Optional[str] = Field(None, description="Gross weight of the vehicle")
    unladen_weight: Optional[str] = Field(None, description="Unladen weight of the vehicle")
    type_of_body: Optional[str] = Field(None, description="Type of body of the vehicle")
    overhang: Optional[str] = Field(None, description="Overhang details of the vehicle")
    tire_size_front: Optional[str] = Field(None, description="Front tire size")
    tire_size_rear: Optional[str] = Field(None, description="Rear tire size")
    vehicle_dimensions: Optional[str] = Field(None, description="Vehicle dimensions (length, width, height)")
    printed_date: Optional[date] = Field(None, description="Date printed in YYYY-MM-DD format")